Check Create_Own_pkl_file.ipynb file to get the pkl file used here.

In [11]:
import pandas as pd
import numpy as np
import pickle
from sklearn.metrics.pairwise import cosine_similarity


def reduce_memory(df):
    for col in df.columns:
        if df[col].dtype == 'float64':
            df[col] = df[col].astype('float32')
        if df[col].dtype == 'int64':
            df[col] = df[col].astype('int32')
    return df

games = reduce_memory(pd.read_csv('./final_games_data_forDesc.csv'))
n_recommendation = 20
vectors = pickle.load(open("./vectors_forDesc_final.pkl",'rb'))

# similarity=pickle.load(open("C:/Users/user/Desktop/recommendation/steam-recommendation/backend/static/src/similarity_forDesc.pkl",'rb'))

# def recommend(game):
#     index = games[games['title'] == game].index[0]
#     sim_scores = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
#     print(sim_scores)
#     game_lists=[]
#     for i in sim_scores[1:n_recommendation]:
#         game_lists.append(games.iloc[i[0]].title)
#     return game_lists
def recommend(game):
    index = games[games['title'] == game].index[0]

    item_vector = vectors[index]
    similarities = cosine_similarity(item_vector, vectors).flatten()
    print(similarities)
    recommended_indices = similarities.argsort()[::-1]  # Get the indices of the most similar items
    print(recommended_indices)
    print(similarities[recommended_indices])
    for i in recommended_indices[1:n_recommendation]:
        print(games.iloc[i].title)

recommend('God Sword')

[0.14711597 0.12019874 0.04289989 ... 0.15500517 0.00997683 0.09296172]
[16743 10213 16964 ... 16950  7613 14480]
[1.         0.42751264 0.42734331 ... 0.         0.         0.        ]
灵途
新魔剑（New Magic Sword）
VR Parallel World
Ethyrial: Echoes of Yore
西部幻想 WestFantasy
Vantage: Primitive Survival Game
Big Sword Hero
Legendary Realms: A Fantasy World Odyssey
神徒
The RPG Engine
Uptown Outbreak
奇迹一刻 Surmount
AOI
Trashyard
Avalom: Ancestral Heroes
Danganronpa S: Ultimate Summer Camp
Wyvern
契约唤灵师
Soulash


In [12]:
recommend("Call of Duty®: Black Ops Cold War")

[0.08461538 0.05640274 0.07850929 ... 0.07015456 0.16432361 0.07939182]
[ 2145  2162  2152 ...  8755  2248 14729]
[1.         0.61782654 0.52787967 ... 0.01614966 0.01591512 0.01247047]
Call of Duty®: Modern Warfare®
Call of Duty®: Vanguard
Tactical Operations Force
The Undisputables : Online Multiplayer Shooter
Call of Duty®: Modern Warfare® II
Cyberfrags '69
Burst Squad
World Of Stalkers
Warplanes: Battles over Pacific
The Last War
Battle Strike World War
PIRATECRAFT
IronSurvival
Fire On Fight : Online Multiplayer Shooter
Wrestledunk Sports
Gambit!
TheDark
EA SPORTS™ FIFA 23
Warcos


In [ ]:
recommend("Animal Academy")